# -*- coding: utf-8 -*-
# Python calls ADB system command to test Android Application

import os
import subprocess

from adb.checkpath import get_sys_env
from utils.logger import logger

__author__ = "joe-tester"

find = get_sys_env()


@logger("Kill all processes")
def app_force_stop(package_name):
    """Stop app running"""
    cmd = 'adb shell am force-stop %s' % (package_name)
    os.system(cmd)


# 	os.system(cmd) # The return value is the exit status code of the script. There will only be 0 (success), 1,2
# 	os.popen(cmd) # Returns the output of the script execution as the return value
# 	subprocess.call('adb shell am force-stop %s' %(package_name), shell=True)


@logger("Back in the background")
def app_force_stop_hot(package_name):
    """background"""
    cmd = 'adb shell input keyevent 3'
    os.system(cmd)


@logger('Time consuming for cold start app acquisition')
def starttime_app(packagename, packagenameactivicy):  # Startup time
    # Forced exit: start/stop app
    app_force_stop(packagename)
    # start app
    cmd = 'adb shell am start -W -n %s/%s' % (packagename, packagenameactivicy)
    me = os.popen(cmd).read().split('\n')[-4].split(':')  # Get start time
    # Forced exit: start/stop app
    app_force_stop(packagename)
    return me


@logger('Time consuming for hot start app acquisition')
def starttime_app_hot(packagename, packagenameactivicy):
    """The premise must be that the app process has been started"""
    # Hot start/stop APP
    app_force_stop_hot()
    # start app
    cmd = 'adb shell am start -W -n %s/%s' % (packagename, packagenameactivicy)
    me = os.popen(cmd).read().split('\n')[-4].split(':')  # get start time
    # Hot start/stop APP
    app_force_stop_hot()
    return me


@logger("get total meminfo")
def get_total_mem():
    t_mem = "adb shell cat /proc/meminfo |%s MemTotal" % find
    t_mem = os.popen(t_mem).read().split()[1]
    return t_mem


@logger('get cpuinfo')
def get_cpu(packagename):
    # Here is the parameter that can be taken when collecting CPU information, that is - N - D refresh interval
    cmd_t = 'adb shell top -n 1 | %s "%s"' % (find, packagename)
    # ['28779', 'u0_a138', '10', '-10', '3.1G', '455M', '269M', 'R', '160', '12.0', '238:07.14', 'com.xxxx.xxxx']
    cpu_p = os.popen(cmd_t).read().split()[8]
    return cpu_p


@logger('get meminfo')
def get_mem(packagename):
    # Physical memory actually used
    cmd_t = 'adb shell top -n 1| %s "%s"' % (find, packagename)
    mem_p = os.popen(cmd_t).read().split()[9]
    return mem_p


@logger('get meminfo')
def get_cpu_mem(packagename):
    # Obtain the usage proportion of CPU and MEM at the same time
    # RES  SHR S [%CPU] %MEM
    # RES - SHR
    # %MEM * TotalMem ≈ RES
    cmd_t = 'adb shell top -n 1| %s "%s"' % (find, packagename)
    line = os.popen(cmd_t).read().split()
    cpu_p = line[8]
    mem_p = line[9]
    return cpu_p, mem_p


@logger('get meminfo2')
def get_mem1(packagename):
    # app use memory actually used ; this method get data is too slow
    cmd_t = 'adb shell dumpsys meminfo|%s %s' % (find, packagename)
    mem_t = os.popen(cmd_t).read().split()[0][:-2].replace(",", "")
    return int(mem_t)


@logger('Get traffic')
def get_netflow(packagename):
    """There is no silver here"""
    # Get the userID to start the app
    cmd = 'adb shell dumpsys package  "%s" | findstr "userId"' % (packagename)
    cm = os.popen(cmd).read().split('=')[1].strip()
    cmd1 = 'adb shell cat /proc/net/xt_qtaguid/stats |%s %s' % (find, cm)
    flow_rec1 = os.popen(cmd1).read().split()[5]  # rec
    flow_snd1 = os.popen(cmd1).read().split()[7]  # send
    cmd2 = 'adb shell cat /proc/net/xt_qtaguid/stats | %s %s' % (find, cm)
    flow_rec2 = os.popen(cmd2).read().split()[5]  # rec
    flow_snd2 = os.popen(cmd2).read().split()[7]  # send
    # The flow generated by the process is calculated as the flow after execution - the flow before execution
    netflow_rec_s = (int(flow_rec1) + int(flow_rec2))
    netflow_snd_s = (int(flow_snd1) + int(flow_snd2))
    netflow_sum = int(netflow_snd_s) - int(netflow_rec_s)
    me1 = int(flow_snd1) - int(flow_rec1)
    me2 = int(flow_snd2) - int(flow_rec2)
    return me1, me2, netflow_sum


@logger('Get traffic2')
def get_netflow1(package):
    """get total netflow; but mobilePhone not has uid_stat dir"""
    cmd = 'adb shell dumpsys package  "%s" | findstr "userId"' % (package)
    uid = os.popen(cmd).read().split('=')[1].strip()  # get application's userId
    # Get download traffic
    c = 'adb shell cat /proc/uid_stat/%s/tcp_rcv' % uid
    p1 = subprocess.Popen(c, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    print(p1.stdout.read())
    flo_rec = float(p1.stdout.read())
    # Get upload traffic
    d = 'adb shell cat /proc/uid_stat/%s/tcp_snd' % uid
    p1 = subprocess.Popen(d, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    flo_snd = float(p1.stdout.read())
    netflow_t = flo_rec + flo_snd  # download plus upload is total traffic
    return flo_snd, flo_rec, netflow_t


@logger("get app pid")
def get_pid(packagename):
    cmd = 'adb shell ps|%s %s' % (find, packagename)
    pid = os.popen(cmd).read().split()[1]
    return pid


@logger('Get traffic3')
def get_netflow2(pid, wlan="wlan0"):
    """A new method for calculating flow"""
    # first of collectInfo
    c1 = 'adb shell cat /proc/%s/net/dev |findstr %s' % (pid, wlan)
    line1 = os.popen(c1).read().split()
    rcv_init = line1[1]
    send_init = line1[9]
    # second of collectInfo
    c2 = 'adb shell cat /proc/%s/net/dev |findstr %s' % (pid, wlan)
    line2 = os.popen(c2).read().split()
    rcv_last = line2[1]
    send_last = line2[9]
    # count netflow
    rcv = float(rcv_last) - float(rcv_init)
    send = float(send_last) - float(send_init)
    total = rcv + send
    return rcv, send, total


@logger("battery test set status=1")
def set_battery_status():
    cmd = 'adb shell dumpsys battery set status 1'
    os.popen(cmd)


@logger("get battery")
def get_battery():
    cmd = 'adb shell dumpsys battery | %s %s' % (find, "level")
    batt = os.popen(cmd).read().split()[1]
    return batt


@logger('Execute monkey test')
def adb_monkey(pkname, s_num, throttle, pct_touch, pct_motion, pct_trackball, pct_nav, pct_majornav, pct_syskeys,
               pct_appswitch, pct_flip, pct_anyevent, times, logfilepath):
    """adb shell monkey -p {0} -s {1} --throttle {2} --pct-touch {3} --pct-motion {4} --pct-trackball  {5}  --pct-nav {6}  
    --pct-majornav {7} --pct-syskeys {8} --pct-appswitch {9}  --pct-flip  {10}  --pct-anyevent {11} -v -v -v {12} >{13}"""
    cmden = 'adb shell monkey -p {0} -s {1} --throttle {2} --pct-touch {3} --pct-motion {4} --pct-trackball  {5}  --pct-nav {6} --pct-majornav {7} --pct-syskeys {8} --pct-appswitch {9}  --pct-flip  {10}  --pct-anyevent {11} -v -v -v {12} >{13}'.format(
        pkname, s_num, throttle, pct_touch, pct_motion, pct_trackball, pct_nav, pct_majornav, pct_syskeys,
        pct_appswitch, pct_flip, pct_anyevent, times, logfilepath)
    os.popen(cmden)


@logger('get device status')
def get_device_status():
    cmd1 = 'adb get-state'
    devices_status = os.popen(cmd1).read().split()[0]
    return devices_status